swagger:
  enable: true
  basePackage: com.hh.springmavendemo.controller
  title: User Login
  description: API DOC of User Login
  version: v1.0

login:
  auth:
    app-passes:
      - { app-id: 101, app-secret: 101 }
      - { app-id: 102, app-secret: 102 }

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/migratelogin?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/userlogin?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: zqx22588
    driver-class-name: com.mysql.jdbc.Driver
  flyway:
    baseline-on-migrate: true
    enabled: false
  output:
    ansi:
      enabled: always

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.hh.springmavendemo.dao

logging:
  config: classpath:log4j2/log4j2-spring.xml
  level:
    root: debuf
    com.hh.springmavendemo.dao: debug